### ISSUE TITLE
能否增加一个按键超过多长时间后就失效的功能

### ISSUE THREAD

**Issue by zsedcbm** [yingDev/WGestures#30]
能否增加一个按键超过多长时间后就失效的功能,有时候需要使用到鼠标中键进行多列编辑,结果得先关掉软件才行,这样挺麻烦的.

**Comment by yingDev** [comment]
本来就有：起始超时。
另外，按鼠标左键 + 中建 可以快速暂停/继续。

**Comment by zsedcbm** [comment]
看到设置项了,之前居然没有注意到...
