### ISSUE TITLE
为何需要安装根证书？

### ISSUE THREAD

**Issue by ZClive** [yingDev/WGestures#7]
请问一下开发者，为什么`WGestures`需要安装根证书？

**Comment by yingDev** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ee671610%28v=vs.85%29.aspx#uiaccess_requirements_for_assistive_technology_applications_

>  To use UIAccess, an assistive technology application needs to:
>  * Be signed with a certificate to interact with applications running at a higher privilege level.
>  * Be trusted by the system and run with administrative privileges. The application must be installed in a secure location that requires a user account control (UAC) prompt to write to (for example, the Program Files folder).

>  ...
