### ISSUE TITLE
您好，更换显示器之后，您的手势软件没有任何效果....

### ISSUE THREAD

**Issue by lzkgbld** [yingDev/WGestures#86]
我尝试给笔记本接入外部显示屏之后，手势软件就失效了，软件是运行正常状态，但是右键滑动已经没有效果...请问有解决方案吗？
![image](https://user-images.githubusercontent.com/46844055/91445375-9af33000-e8a8-11ea-8c85-b46bd4913c68.png)

**Comment by rangluwme** [comment]
你应该是关掉了吧，默认状态下，鼠标放到底部，右键，是可以控制开关的。连接显示器这个无影响的。
